/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `TableContract`'s JSON-Schema
 * via the `definition` "TableEvent".
 */
export type TableEvent = TurnStarted | NarrationDelta | TurnFinished | PartyUpdated | EncounterUpdated | TableError

/**
 * The table's event contract, version 1. Generated from dungeon_master.events.contract by `python -m dungeon_master.events.schema`; do not edit by hand.
 */
export interface TableContract {
  contract_version: 1
  event: TableEvent
  action: DeclaredAction
}
/**
 * A declared action was accepted, and the dungeon master is answering it.
 *
 * This interface was referenced by `TableContract`'s JSON-Schema
 * via the `definition` "TurnStarted".
 */
export interface TurnStarted {
  type: 'turn_started'
  turn_id: string
  action: DeclaredAction
}
/**
 * What a player typed: the declared action and the dice they rolled.
 *
 * This interface was referenced by `TableContract`'s JSON-Schema
 * via the `definition` "DeclaredAction".
 */
export interface DeclaredAction {
  text: string
  /**
   * The acting character, when the client knows it.
   */
  character_id: string | null
}
/**
 * The next piece of narration, as the model writes it.
 *
 * This interface was referenced by `TableContract`'s JSON-Schema
 * via the `definition` "NarrationDelta".
 */
export interface NarrationDelta {
  type: 'narration_delta'
  turn_id: string
  text: string
}
/**
 * The dungeon master has finished answering; the next action may be declared.
 *
 * This interface was referenced by `TableContract`'s JSON-Schema
 * via the `definition` "TurnFinished".
 */
export interface TurnFinished {
  type: 'turn_finished'
  turn_id: string
}
/**
 * The whole party as the backend holds it, after a tool changed it.
 *
 * This interface was referenced by `TableContract`'s JSON-Schema
 * via the `definition` "PartyUpdated".
 */
export interface PartyUpdated {
  type: 'party_updated'
  party: Character[]
}
/**
 * One player character, as the system holds it (ADR-0004).
 *
 * This interface was referenced by `TableContract`'s JSON-Schema
 * via the `definition` "Character".
 */
export interface Character {
  /**
   * Stable identity within the session; tools address the character by it.
   */
  id: string
  name: string
  /**
   * For narration only.
   */
  character_class: string
  /**
   * For narration only.
   */
  level: number
  armour_class: number
  max_hit_points: number
  current_hit_points: number
  temporary_hit_points: number
  conditions: (
    | 'blinded'
    | 'charmed'
    | 'deafened'
    | 'exhaustion'
    | 'frightened'
    | 'grappled'
    | 'incapacitated'
    | 'invisible'
    | 'paralyzed'
    | 'petrified'
    | 'poisoned'
    | 'prone'
    | 'restrained'
    | 'stunned'
    | 'unconscious'
    | 'stable'
    | 'dead'
  )[]
}
/**
 * The public state of the encounter, after a tool changed it.
 *
 * This interface was referenced by `TableContract`'s JSON-Schema
 * via the `definition` "EncounterUpdated".
 */
export interface EncounterUpdated {
  type: 'encounter_updated'
  encounter: Encounter | null
}
/**
 * What the table may know about the encounter (docs/domain/combat.md).
 *
 * The opponent's numbers are not here: they are hidden from the table and
 * belong to the opponent's own state (#31).
 *
 * This interface was referenced by `TableContract`'s JSON-Schema
 * via the `definition` "Encounter".
 */
export interface Encounter {
  opponent_name: string
  /**
   * 0 until the turn order is fixed.
   */
  round: number
  turn_order: Combatant[]
  /**
   * Index into turn_order of whoever acts now.
   */
  current_turn: number | null
  /**
   * Set when the encounter has ended.
   */
  outcome: ('opponent_defeated' | 'opponent_fled' | 'party_fled' | 'party_defeated' | 'parley') | null
}
/**
 * One place in the turn order.
 *
 * This interface was referenced by `TableContract`'s JSON-Schema
 * via the `definition` "Combatant".
 */
export interface Combatant {
  kind: 'character' | 'opponent'
  id: string
  name: string
}
/**
 * Something went wrong that the table should know about.
 *
 * The message is written for the table. It never carries an exception's
 * text, which could carry a credential (ADR-0007).
 *
 * This interface was referenced by `TableContract`'s JSON-Schema
 * via the `definition` "TableError".
 */
export interface TableError {
  type: 'error'
  code: 'agent_failed'
  message: string
  turn_id: string | null
}
